---
driver:
  name: vagrant
  vm_hostname: checkmk
  customize:
    memory: <%= ENV['CHEF_RAM'] %>
    cpus: <%= ENV['CHEF_CPU'] %>
    name: checkmk
  network:
   - ['private_network', ip: '10.1.1.101']

provisioner:
  name: chef_zero
  product_name: chef
  product_version: <%= ENV['chef_release'] %>
  deprecations_as_errors: true
  chef_license: accept-no-persist

verifier:
  name: inspec

platforms:
  - name: mycentos7
    provisioner:
      download_url: http://10.1.1.30/media/chef-<%= ENV['chef_release'] %>-1.el7.x86_64.rpm

suites:
  - name: checkmk
    run_list:
      - recipe[checkmk::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
